### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#12]
![9 - checkbox](https://cloud.githubusercontent.com/assets/6860415/19434155/35616d34-9464-11e6-8e1b-7a1f3139bb79.png)

**Comment by dltmd6262** [comment]
Added component to library, still need to find where it's being used.

**Comment by MogilevichDmitry** [comment]
text may be bold and normal
just add state and classname `` if state is bold
and then i'll add classname to the styles

**Comment by MogilevichDmitry** [comment]
Added props `isLabelBold` https://github.com/adamryvola/shared-components/pull/24/commits/e34e5a6cc1620066f8cfa654a9e066f01f1e54d8
