### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#15]
1) All is implemented in apps - find it
2) move it to shared-components repo
3) integrate - use button from shared-components
![image](https://cloud.githubusercontent.com/assets/6860415/19452571/c18c5c4a-94b1-11e6-9ee1-ec1bca9cd242.png)

**Comment by MogilevichDmitry** [comment]
15. ToggleBtn only to thre right 
![image](https://cloud.githubusercontent.com/assets/11472088/19469447/09606454-9524-11e6-80d0-54ec3483c883.png)

And new button 
16. ScrollBtn
![image](https://cloud.githubusercontent.com/assets/11472088/19469476/26d5770e-9524-11e6-92ba-0704c7b9d099.png)

you can ask me where to find these buttons on projects :)

**Comment by Daniellt1** [comment]
I trying to implement SocialButton component into SHARING-PORTAL project. Current version of this component in the project looks like:
`<SocialButton type="GOOGLE" onClick={onGoogleLogin} />`
However, component from shared-components not uses onClick prop, but have a hardcoded href. Should this component be refactored? Or integrate it as it is now?

**Comment by adamryvola** [comment]
Hardcoded link is correct.

**Comment by MogilevichDmitry** [comment]
- 17.ChatBtn ![image](https://cloud.githubusercontent.com/assets/11472088/19573090/75acd0d0-970d-11e6-992f-95668795131d.png)

- 18.ChatIcoBtn ![image](https://cloud.githubusercontent.com/assets/11472088/19573152/b7ecba6e-970d-11e6-9f9b-1ef3540c97c3.png)

- 19.SaveBtn ![image](https://cloud.githubusercontent.com/assets/11472088/19573147/b4362ab8-970d-11e6-8ecd-de82f48d0a8f.png)


- 10.CancelBtn needs to be implemented in two color embodiments
red as the above
and gray ![image](https://cloud.githubusercontent.com/assets/11472088/19573236/16997c0a-970e-11e6-9a8e-feb04620dd52.png) 

All here 
http://edookit-space.herokuapp.com/
http://edookit-space.herokuapp.com/https://edookit-space.herokuapp.com/user-profile

**Comment by MogilevichDmitry** [comment]
- SocialBtn may take text, like here 

![image](https://cloud.githubusercontent.com/assets/11472088/19604149/bbb4ded8-97bc-11e6-888d-50dd243f1efe.png)
