### ISSUE TITLE
Selector 

### ISSUE THREAD

**Issue by MogilevichDmitry** [adamryvola/shared-components#19]
https://edookit-schools-dev.herokuapp.com/selector
![image](https://cloud.githubusercontent.com/assets/11472088/19617740/03144190-9841-11e6-9013-49e4e46a21b9.png)
if the code is responsible for functional bad, you can do what you think is necessary.

**Comment by MogilevichDmitry** [comment]
You can find code here https://github.com/adamryvola/school-picker/tree/master/app/components/Selector

**Comment by adamryvola** [comment]
done
https://adamryvola.github.io/shared-components/#Selector
