### ISSUE TITLE
Better export

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#2]
Current useage of package:
1) npm install ...
2) import Components from 'shared-components';
3) <Components.SocialButton />

But we want to use it like:
import SocialButton from 'shared-components'

I think it will be little change in exports.

**Comment by Daniellt1** [comment]
Done on the better-exports-test branch. Because of the fact that the way how components need to be imported is changed - merge can break project which already use that module.

**Comment by adamryvola** [comment]
Please write new README.md how to use this repo. With examples please.

**Comment by adamryvola** [comment]
README.md is DONE - Thanks.

Please clean repo, I mean please delete useless components: Test Component, ButtonComponent

**Comment by adamryvola** [comment]
AppBadgeButton -> add example please

**Comment by adamryvola** [comment]
Add all AppBadgeButton possibilities (+ apple, microsoft).
Example of SearchFormTag has different font - fix it please.

**Comment by adamryvola** [comment]
SocialButton -> make Google example as link to "#"

**Comment by Daniellt1** [comment]
Can't really make SocialButton as a link to '#' because it has hardcoded url: href={"/api/auth/"+this.props.type.toLowerCase()}. Do you want me to refactor the component?

**Comment by adamryvola** [comment]
No, it is no problem
