### ISSUE TITLE
Tags input

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#3]
You can find tags input component in school-picker.
Move this component to this repo (make it sharable between projects) and integrate this repo to school-picker and edookit-chat and use tags input from this repo.
(Write and generate docs - everytime)

**Comment by adamryvola** [comment]
Please change functionality of this component. Now it works like:
1) type some text
2) press enter to create tag
3) click on button for search

But we want that it will work like:
1) type some text
2) press space create tag
3) press enter or click button for search

The main difference will be, that we won't support tags with more than one word.

**Comment by Daniellt1** [comment]
SearchForm component is now integrated into the app. However, currently we are passing dummy props to it. The thing is that not sure how this form going to be used in this app and if it is still worth to use selected approach for handling the search (as it works in school-picker). I think, we need to have a discuss before we can proceed with this component.

**Comment by adamryvola** [comment]
add attribute placeholder, default value will be current value

**Comment by adamryvola** [comment]
show placeholder just when input is empty, something like:
placeholder={this.props.query.length === 0 ? this.props.placeholder : ""}
