### ISSUE TITLE
Menu (With MenuList)

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#5]
You can find it on right-top corner: https://edookit-chat-dev.herokuapp.com/
Ask Adam about access to chat repo

![2 - menu menulist](https://cloud.githubusercontent.com/assets/6860415/19433740/3c7d07e2-9462-11e6-8658-b69b25e6b4ec.png)

**Comment by MogilevichDmitry** [comment]
we need a menu button in two color options
white as a http://edookit-space.herokuapp.com/
and blue as a https://edookit-chat-dev.herokuapp.com/

**Comment by Joran182to** [comment]
Added component to library, still need to find where it's being used.
