### ISSUE TITLE
ProfileMobileTabs 

### ISSUE THREAD

**Issue by MogilevichDmitry** [adamryvola/shared-components#50]
Addto shared-components new component ProfileMobileTabs from https://github.com/adamryvola/school-picker/tree/master/app/components/ProfileMobileTabs

**Comment by MogilevichDmitry** [comment]
Sorry i forgot add a keys 

>           items.map((item, index) =>
>             <button
>               ...
>               key={index}
>             >
>              ...
>             </button>
>           )
>

**Comment by adamryvola** [comment]
DONE
https://adamryvola.github.io/shared-components/#ProfileMobileTabs

TODO: integrate into school-picker and others

**Comment by MogilevichDmitry** [comment]
Added into school-picker 
Add new propery: handler 
DONE
