### ISSUE TITLE
Add StepsBar

### ISSUE THREAD

**Issue by MogilevichDmitry** [adamryvola/shared-components#59]
All code here
https://github.com/adamryvola/edookit-space/blob/master/app/components/SignUp/StepsBar.js
https://github.com/adamryvola/edookit-space/blob/master/app/components/SignUp/steps-bar.less

**Comment by MogilevichDmitry** [comment]
I was a little altered
If the functional part is not optimal, you can adjust as you see fit

https://github.com/adamryvola/SHARING-PORTAL/tree/webpack-hr-native-build/app/components/StepsBar

**Comment by adamryvola** [comment]
Component added, problem with more than 3 steps

**Comment by MogilevichDmitry** [comment]
Problem with more than 3 steps is fixed.
