### ISSUE TITLE
Notification with NotificationList

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#6]
http://edookit-space.herokuapp.com/ -> Click on login via google, after login look at right top corner - after click on bell you will see list of notifications

![3 - notifications](https://cloud.githubusercontent.com/assets/6860415/19433831/a25a4ee4-9462-11e6-8352-d859db97e745.png)

**Comment by MogilevichDmitry** [comment]
we need a notification button in two color options
white as a http://edookit-space.herokuapp.com/
and blue as a https://edookit-chat-dev.herokuapp.com/

**Comment by Joran182to** [comment]
Added component to library, still need to find where it's being used. Also, there is an issue with styles of counter in notifications (https://adamryvola.github.io/shared-components/#Notifications) @MogilevichDmitry

**Comment by MogilevichDmitry** [comment]
Fixed

**Comment by MogilevichDmitry** [comment]
Fixed bug if count = 0 
![image](https://cloud.githubusercontent.com/assets/11472088/19961756/4c90d076-a1c5-11e6-9544-2eed06860ac3.png)

https://github.com/adamryvola/shared-components/commit/f06f2329c16b58147c55c39eb373d775a0abfa94
