### ISSUE TITLE
MultipleSelector

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#8]
https://edookit-schools-dev.herokuapp.com/selector

![5 - multipleselector](https://cloud.githubusercontent.com/assets/6860415/19433966/4b9dad3e-9463-11e6-9a99-e284e2b79a50.png)

**Comment by MogilevichDmitry** [comment]
new route https://edookit-schools-dev.herokuapp.com/multi-selector

**Comment by zenway-js** [comment]
- Adding multi-selector. Not done yet.

**Comment by zenway-js** [comment]
- Add multi-selector. Submitted PR.

**Comment by adamryvola** [comment]
- https://adamryvola.github.io/shared-components/#!/MultiSelector -> doesnt show options
- https://adamryvola.github.io/shared-components/#!/MultiSelectorList -> ugly example, solve overflow
- https://adamryvola.github.io/shared-components/#MultiSelectorListItem

all of these:
- select works just with click on text, doesn't work with click on square
- bad font in example

**Comment by MogilevichDmitry** [comment]
Need to add props for multiselector without start title like this

![image](https://cloud.githubusercontent.com/assets/11472088/20091556/703d7758-a5a4-11e6-8d5e-9c419dfadbd1.png)

**Comment by adamryvola** [comment]
Done
https://adamryvola.github.io/shared-components/#MultiSelector
