### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#9]
https://edookit-schools-dev.herokuapp.com/schools/1#discussions

Implement full functionality - add comment, reply..

![6 - discussion](https://cloud.githubusercontent.com/assets/6860415/19434021/867ad15c-9463-11e6-81e5-06ddbaa652ab.png)

**Comment by zenway-js** [comment]
- Working on adding Discussions component. Not done yet.
- Fixed all autofixable eslint issues.
